---
- name: Install nmtrust
  become: true
  kewlfft.aur.aur:
    name: nmtrust-git
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Create nmtrust config directory
  ansible.builtin.file:
    path: /etc/nmtrust
    state: directory
  become: true

- name: Push trusted network list
  ansible.builtin.template:
    src: trusted_networks.j2
    dest: /etc/nmtrust/trusted_networks
  become: true

- name: Verify trusted unit list exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/nmtrust/trusted_units
    force: false
  become: true
