- name: Enable and start {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    state: started
  when: run_on == "all" and user_unit is not defined
  become: true

- name: Disable {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: false
  when: run_on != "all" and user_unit is not defined
  become: true

- name: Add to trusted unit list - {{ unit }}
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: present
    line: "{{ unit }}"
  when: run_on == "trusted" and user_unit is not defined
  become: true

- name: Remove from trusted unit list - {{ unit }}
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: absent
    line: "{{ unit }}"
  when: run_on != "trusted" and user_unit is not defined
  become: true

- name: Enable and start for user - {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: run_on == "all" and user_unit is defined and user_unit

- name: Disable for user - {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: false
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: run_on != "all" and user_unit is defined and user_unit

- name: Add for user to trusted unit list - {{ unit }}
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: present
    line: "{{ unit }},user:{{ user.name }}"
  when: run_on == "trusted" and user_unit is defined and user_unit
  become: true

- name: Remove for user from trusted unit list - {{ unit }}
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: absent
    line: "{{ unit }},user:{{ user.name }}"
  when: run_on != "trusted" and user_unit is defined and user_unit
  become: true
