hosts_pack: basic
thinkpad: true
user: dnewman
uid: 1000
hostname: rodimus
bootloader: grub
sudo_without_password: true
github_user: floatingman
ssh_key_name: "id_ed25519_dlp"
ssh_key_path: "{{ user }}/.ssh/{{ ssh_key_name }}"
gitconfig:
  name: Daniel Newman
  mail: dan@danlovesprogramming.com
  delta: true
  neovim_remote: true
  meld: true
dotfiles:
  repo_url: git@github.com:{{ github_user }}/dotfiles.git
  path: "{{ user }}/.dotfiles"
  rcup_flags: -fx README.md
  linuxgui: true
kernel_parameters: "quiet consoleblank=60 i915.enable_psr=2"
network:
  conn_check:
    interval: 5
  trusted_uuid:
    - 5619b099-2c22-3276-8a7a-f12f55976a81
    - 97a225df-f8f9-4fc4-a95d-289654f71c02
video_drivers:
    - vulkan-icd-loader
    - vulkan-intel
    - vulkan-mesa-layers
    - vulkan-tools
    - intel-media-driver
    - libva-intel-driver
browser_choices:
    - firefox -P default-release
    - firefox -P work
    - chromium
    - qutebrowser
    - tor-browser-en
    - play
    - qcode
    - "| xclip -selection c"
display_manager: gdm
gdm:
    sound: False
    font_scaling_factor: 1
    logo_path: False
    touchpad:
        tap_to_click: True
    accessibility_menu: True
desktop_environment: gnome
gnome:
    night_light:
        enabled: True
        color_temperature: 4000 # in Kelvin
    date_time:
        show_date_in_clock: True
        show_weeks_in_calendar: True
    battery:
        show_percentage: True
    power:
        sleep_timeout_when_computer_on_ac: 3600 # in seconds
        timeout_action_when_computer_on_ac: suspend
        sleep_timeout_when_computer_on_battery: 1800 # in seconds
        timeout_action_when_computer_on_battery: suspend
        power_button_action: suspend
    touchpad:
        tap_to_click: True
        natural_scrolling: True
        disabled_while_typing: True
    online_accounts_support: True
    lock_screen:
        automatic_lock: True
        lock_screen_after_blank_for: 0 # in seconds
        show_notifications: True
        show_full_name_of_user: True
    theme:
        theme_name: Adwaita
        icon_theme_name: Adwaita
        font_name: Dejavu Sans 13
        dark_variant: True
    gnome_shell:
        disable_top_left_hot_corner: False
        extensions_support: True
lang:
  enabled: true
  arch:
    - python
    - python-pip
    - go
goesimage:
  run_time: 15min
  run_boot_delay: 2min
  run_on: trusted
  flags: -w -e
gui:
  enabled: true
  arch:
    - alacritty
    - bitwarden
    - bspwm
    - caffeine-ng
    - clipmenu
    - dunst
    - exiv2
    - geeqie
    - hledger
    - hledger-ui
    - hsetroot
    - i3-gaps
    - inkscape
    - intel-ucode
    - inxi
    - isync
    - libreoffice
    - libva-utils
    - linux-firmware
    - linux-headers
    - manjaro-printer
    - mariadb-clients
    - mesa
    - mesa-demos
    - pinta
    - powertop
    - polybar
    - sof-firmware
    - sxhkd
    - sxiv
    - syncthing
    - system-config-printer
    - ttf-jetbrains-mono
    - udevil
    - urlscan
    - viewnior
    - wmctrl
    - xbindkeys
    - xsettingsd
    - xcape
    - xf86-input-synaptics
    - xorg-xinput
    - xorg-xwininfo
    - zathura-pdf-mupdf
cli:
  enabled: true
  common:
    - bison
    - coreutils
    - curl
    - cmake
    - dateutils
    - dnsutils
    - docker
    - emacs
    - fdupes
    - figlet
    - flex
    - htop
    - hugo
    - iftop
    - iotop
    - ipcalc
    - keychain
    - lsof
    - mdp
    - moreutils
    - mpv
    - msmtp
    - neomutt
    - newsboat
    - notmuch
    - notmuch-mutt
    - npm
    - pandoc
    - pdfgrep
    - pkg-config
    - pwgen
    - rsync
    - shellcheck
    - sshfs
    - strace
    - sudo
    - surfraw
    - time
    - tmux
    - translate-shell
    - trash-cli
    - tree
    - vifm
    - w3m
    - wget
    - whois
    - zip
  debian:
    - dnsutils
    - exuberant-ctags
    - libxfixes-dev
    - x11proto-core-dev
    - libx11-dev
    - libxt-dev
    - libxfixes-dev
    - libxi-dev
    - texlive
    - libxext-dev
    - timewarrior
  arch:
    - ctags
    - bitwarden-cli
    - bind-tools
    - entr
    - prettier
    - texlive-core
    - exa
    - hey
    - argocd
    - bat
    - broot
    - bottom
    - git-delta
    - direnv
    - docker-compose
    - doctl
    - dog
    - dua-cli
    - duf
    - dust
    - fd
    - fluxctl
    - github-cli
    - gitui
    - glab
    - jq
    - k9s
    - kube-linter
    - kubectx
    - kubeseal
    - kustomize
    - lazygit
    - logcli
    - mdbook
    - nnn
    - popeye
    - prettyping
    - rclone
    - ripgrep
    - ripgrep-all
    - sd
    - stern
    - tectonic
    - texlab
    - timew
    - tokei
    - xsv
    - yq
    - youtube-dl
    - zoxide
pip_packages:
  - "molecule[docker]"
  - aws-shell
  - flake8
  - gita
  - gitlabber
  - grip
  - httpie
  - ipython
  - jedi
  - jedi-language-server
  - jupyterlab
  - khal
  - khard
  - matplotlib
  - molecule
  - mycli
  - neovim-remote
  - pandas
  - python-rofi
  - selenium
  - s4cmd
  - speedtest-cli
  - pytest-testinfra
  - ueberzug
  - yamllint
  - vdirsyncer
aur:
  packages:
    - synergy-git
    - dropbox
    - awless
    - aws-iam-authenticator-bin
    - bit
    - dive
    - dyff-bin
    - git-quick-stats
    - highlight-pointer-git
    - k6
    - kind
    - kops-bin
    - kubeval-bin
    - lf
    - nova
    - pet-bin
    - polaris-bin
    - scc
    - slack-term-bin
    - tflint-bin
    - tfswitch-bin
    - viddy
    - masterpdfeditor
    - urlview
    - telepresence
    - visual-studio-code-bin
    - glow
    - google-cloud-sdk
    - postman
    - nerd-fonts-hack
    - nerd-fonts-fira-code
    - xbanish
asdf_user: "{{ user }}"
asdf_plugins:
  - name: "nodejs"
    versions:
      - 17.7.1
    global: 17.7.1
  - name: "ruby"
    versions:
      - 3.1.1
    global: 3.1.1
  - name: "kubectl"
    versions:
      - 1.23.4
    global: 1.23.4
  - name: "terraform"
    versions:
      - 1.1.8
    global: 1.1.8
  - name: "helm"
    versions:
      - 3.8.0
    global: 3.8.0
  - name: "concourse"
    versions:
      - 7.7.0
    global: 7.7.0
  - name: "packer"
    versions:
      - 1.8.0
    global: 1.8.0
  - name: "minikube"
    versions:
      - 1.25.2
    global: 1.25.2
  - name: "aws-vault"
    repository: https://github.com/markosamuli/asdf-aws-vault.git
    versions:
      - 4.6.2
    global: 4.6.2
pyenv_env: "user"
pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
pyenv_owner: "{{ ansible_env.USER }}"
pyenv_global: "3.10.3"
pyenv_update: yes
pyenv_update_git_install: yes
pyenv_enable_autocompletion: no
pyenv_python_versions:
  - "3.10.3"
  - "2.7.18"
pyenv_virtualenvs:
  - venv_name: "py3nvim"
    py_version: "3.10.3"
  - venv_name: "py2nvim"
    py_version: "2.7.18"

argocdcli_version: 2.3.1
awless_version: 0.1.11
bat_version: 0.20.0
bit_version: 1.1.2
bottom_version: 0.6.8
delta_version: 0.12.1
direnv_version: 2.30.3
dive_version: 0.10.0
docker_compose_version: v2.3.3
docker_version: 20.10.13
doctl_version: 1.71.1
dua_version: 2.17.0
dog_version: v0.1.0
duf_version: 0.8.1
dust_version: 0.8.1-alpha.2
dyff_version: 1.5.1
exa_version: 0.10.1
fd_version: v8.3.2
fluxctl_version: 1.24.3
githubcli_version: 2.6.0
gitui_version: 0.20.1
glab_version: 1.22.0
helm_version: 3.8.1
highlight_pointer_version: 1.1.3
istioctl_version: 1.13.2
jq_version: 1.6
k6_version: v0.37.0
k9s_version: 0.25.18
kind_version: 0.12.0
kops_version: 1.23.0
kube_linter_version: 0.2.5
kubectl_version: 1.23.0
kubectx_version: v0.9.4
kubens_version: v0.9.4
kubeseal_version: 0.17.3
kubeval_version: 0.16.1
kustomize_version: 4.5.2
lazygit_version: 0.34
lf_version: r26
mdbook_version: 0.4.15
nnn_version: 4.4
nova_version: 3.0.2
pet_version: 0.4.0
polaris_version: 5.1.0
popeye_version: 0.9.8
ripgrep_version: 13.0.0
rke_version: v1.3.10 
scc_version: 3.0.0
sd_version: 0.7.6
slack_term_version: 0.5.0
stern_version: 1.11.0
tectonic_version: 0.8.2
texlab_version: v3.3.2
tflint_version: v0.34.1
tfswitch_version: 0.13.1218
tokei_version: 12.1.2
xsv_version: 0.13.0
viddy_version: 0.3.4
yq_version: 4.22.1
zoxide_version: 0.8.0
logcli_version: v2.4.2
binaries:
  - name: hey
    url: "https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64"
    bin_name: hey_linux_amd64

  - name: argocd
    url: "https://github.com/argoproj/argo-cd/releases/download/v{{ argocdcli_version }}/argocd-linux-amd64"
    bin_name: argocd-linux-amd64

  - name: awless
    url: "https://github.com/wallix/awless/releases/download/v{{ awless_version }}/awless-linux-amd64.tar.gz"
    extract: true

  - name: aws-iam-authenticator
    url: "https://amazon-eks.s3-us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator"

  - name: bat
    url: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu.tar.gz"
    bin_path: "bat-v{{ bat_version }}-x86_64-unknown-linux-gnu"
    extract: true

  - name: bit
    url: "https://github.com/chriswalz/bit/releases/download/v{{ bit_version }}/bit_{{ bit_version }}_linux_amd64.tar.gz"
    extract: true

  - name: broot
    url: "https://dystroy.org/broot/download/x86_64-linux/broot"

  - name: btm
    url: "https://github.com/ClementTsang/bottom/releases/download/{{ bottom_version }}/bottom_x86_64-unknown-linux-gnu.tar.gz"
    extract: true

  - name: delta
    url: "https://github.com/dandavison/delta/releases/download/{{ delta_version }}/delta-{{ delta_version }}-x86_64-unknown-linux-gnu.tar.gz"
    extract: true
    bin_path: "delta-{{ delta_version }}-x86_64-unknown-linux-gnu"

  - name: direnv
    url: "https://github.com/direnv/direnv/releases/download/v{{ direnv_version }}/direnv.linux-amd64"
    bin_name: "direnv.linux-amd64"

  - name: dive
    url: "https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.tar.gz"
    extract: true

  - name: docker-compose
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    bin_name: docker-compose-linux-x86_64

  - name: docker
    url: "https://download.docker.com/linux/static/stable/x86_64/docker-{{ docker_version }}.tgz"
    bin_path: docker
    extract: true

  - name: doctl
    url: "https://github.com/digitalocean/doctl/releases/download/v{{ doctl_version }}/doctl-{{ doctl_version }}-linux-amd64.tar.gz"
    extract: true

  - name: dog
    url: "https://github.com/ogham/dog/releases/download/{{ dog_version }}/dog-{{ dog_version }}-x86_64-unknown-linux-gnu.zip"
    extract: true
    bin_path: bin

  - name: dua
    url: "https://github.com/Byron/dua-cli/releases/download/v{{ dua_version }}/dua-v{{ dua_version }}-x86_64-unknown-linux-musl.tar.gz"
    extract: true
    bin_path: "dua-v{{ dua_version}}-x86_64-unknown-linux-musl"

  - name: duf
    url: "https://github.com/muesli/duf/releases/download/v{{ duf_version }}/duf_{{ duf_version }}_linux_x86_64.tar.gz"
    extract: true

  - name: dust
    url: "https://github.com/bootandy/dust/releases/download/v{{ dust_version }}/dust-v{{ dust_version }}-x86_64-unknown-linux-gnu.tar.gz"
    extract: true
    bin_path: "dust-v{{ dust_version }}-x86_64-unknown-linux-gnu"

  - name: dyff
    url: "https://github.com/homeport/dyff/releases/download/v{{ dyff_version }}/dyff_{{ dyff_version }}_linux_amd64.tar.gz"
    extract: true

  - name: exa
    url: "https://github.com/ogham/exa/releases/download/v{{ exa_version }}/exa-linux-x86_64-v{{ exa_version }}.zip"
    extract: true
    bin_path: "bin"

  - name: fd
    url: "https://github.com/sharkdp/fd/releases/download/{{ fd_version }}/fd-{{ fd_version }}-x86_64-unknown-linux-gnu.tar.gz"
    extract: true
    bin_path: "fd-{{ fd_version }}-x86_64-unknown-linux-gnu"

  - name: fluxctl
    url: "https://github.com/fluxcd/flux/releases/download/{{ fluxctl_version }}/fluxctl_linux_amd64"
    bin_name: fluxctl_linux_amd64

  - name: gh-md-toc
    url: "https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc"

  - name: git-quick-stats
    url: "https://raw.githubusercontent.com/arzzen/git-quick-stats/master/git-quick-stats"

  - name: gh
    url: "https://github.com/cli/cli/releases/download/v{{ githubcli_version }}/gh_{{ githubcli_version }}_linux_amd64.tar.gz"
    extract: true
    bin_path: "gh_{{ githubcli_version }}_linux_amd64/bin"

  - name: gitui
    url: "https://github.com/extrawurst/gitui/releases/download/v{{ gitui_version }}/gitui-linux-musl.tar.gz"
    extract: true

  - name: glab
    url: "https://github.com/profclems/glab/releases/download/v{{ glab_version }}/glab_{{ glab_version}}_Linux_x86_64.tar.gz"
    extract: true
    bin_path: bin

  - name: helm
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    extract: true
    bin_path: linux-amd64/

  - name: highlight-pointer
    url: "https://github.com/swillner/highlight-pointer/releases/download/v{{ highlight_pointer_version }}/highlight-pointer"

  - name: istioctl
    url: "https://github.com/istio/istio/releases/download/{{ istioctl_version }}/istioctl-{{ istioctl_version }}-linux-amd64.tar.gz"
    extract: true

  - name: jq
    url: "https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64"
    bin_name: jq-linux64

  - name: k6
    url: "https://github.com/loadimpact/k6/releases/download/{{ k6_version }}/k6-{{ k6_version }}-linux-amd64.tar.gz"
    extract: true
    bin_path: "k6-{{ k6_version }}-linux-amd64"

  - name: k9s
    url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_x86_64.tar.gz"
    extract: true

  - name: kind
    url: "https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-linux-amd64"
    bin_name: kind-linux-amd64

  - name: kops
    url: "https://github.com/kubernetes/kops/releases/download/v{{ kops_version }}/kops-linux-amd64"
    bin_name: kops-linux-amd64

  - name: kube-linter
    url: "https://github.com/stackrox/kube-linter/releases/download/{{ kube_linter_version }}/kube-linter-linux.tar.gz"
    extract: true

  - name: kubectl
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"

  - name: kubectx
    url: "https://github.com/ahmetb/kubectx/releases/download/{{ kubectx_version }}/kubectx"

  - name: kubens
    url: "https://github.com/ahmetb/kubectx/releases/download/{{ kubens_version }}/kubens"

  - name: kubeseal
    url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ kubeseal_version }}/kubeseal-{{ kubeseal_version }}-linux-amd64.tar.gz"
    extract: true

  - name: kubeval
    url: "https://github.com/instrumenta/kubeval/releases/download/v{{ kubeval_version }}/kubeval-linux-amd64.tar.gz"
    extract: true

  - name: kustomize
    url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz"
    extract: true

  - name: lazygit
    url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    extract: true

  - name: lf
    url: "https://github.com/gokcehan/lf/releases/download/{{ lf_version }}/lf-linux-amd64.tar.gz"
    extract: true

  - name: logcli
    url: "https://github.com/grafana/loki/releases/download/{{ logcli_version }}/logcli-linux-amd64.zip"
    extract: true
    bin_name: logcli-linux-amd64

  - name: mdbook
    url: "https://github.com/rust-lang/mdBook/releases/download/v{{ mdbook_version }}/mdbook-v{{ mdbook_version }}-x86_64-unknown-linux-gnu.tar.gz"
    extract: true

  - name: mgitstatus
    url: "https://raw.githubusercontent.com/fboender/multi-git-status/master/mgitstatus"

  - name: nnn
    url: "https://github.com/jarun/nnn/releases/download/v{{ nnn_version }}/nnn-static-{{ nnn_version }}.x86_64.tar.gz"
    extract: true
    bin_name: nnn-static

  - name: nova
    url: "https://github.com/FairwindsOps/nova/releases/download/{{ nova_version }}/nova_{{ nova_version }}_linux_amd64.tar.gz"
    extract: true

  - name: pet
    url: "https://github.com/knqyf263/pet/releases/download/v{{ pet_version }}/pet_{{ pet_version }}_linux_amd64.tar.gz"
    extract: true

  - name: polaris
    url: "https://github.com/FairwindsOps/polaris/releases/download/{{ polaris_version }}/polaris_linux_amd64.tar.gz"
    extract: true

  - name: popeye
    url: "https://github.com/derailed/popeye/releases/download/v{{ popeye_version }}/popeye_Linux_x86_64.tar.gz"
    extract: true

  - name: prettyping
    url: "https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping"

  - name: ripgrep
    url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz"
    extract: true
    bin_path: "ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl"
    bin_name: rg
  
  - name: rke
    url: "https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64"
    bin_name: rke_linux-amd64

  - name: scc
    url: "https://github.com/boyter/scc/releases/download/v{{ scc_version }}/scc-{{ scc_version }}-x86_64-unknown-linux.zip"
    extract: true

  - name: sd
    url: "https://github.com/chmln/sd/releases/download/v{{ sd_version }}/sd-v{{ sd_version }}-x86_64-unknown-linux-gnu"
    bin_name: "sd-v{{ sd_version }}-x86_64-unknown-linux-gnu"

  - name: slack-term
    url: "https://github.com/erroneousboat/slack-term/releases/download/v{{ slack_term_version }}/slack-term-linux-amd64"
    bin_name: slack-term-linux-amd64

  - name: stern
    url: "https://github.com/wercker/stern/releases/download/{{ stern_version }}/stern_linux_amd64"
    bin_name: stern_linux_amd64

  - name: tectonic
    url: "https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%40{{ tectonic_version }}/tectonic-{{ tectonic_version }}-x86_64-unknown-linux-gnu.tar.gz"
    extract: true

  - name: texlab
    url: "https://github.com/latex-lsp/texlab/releases/download/{{ texlab_version }}/texlab-x86_64-linux.tar.gz"
    extract: true

  - name: tflint
    url: "https://github.com/terraform-linters/tflint/releases/download/{{ tflint_version }}/tflint_linux_amd64.zip"
    extract: true

  - name: tfswitch
    url: "https://github.com/warrensbox/terraform-switcher/releases/download/{{tfswitch_version}}/terraform-switcher_{{tfswitch_version}}_linux_amd64.tar.gz"
    extract: true

  - name: tokei
    url: "https://github.com/XAMPPRocky/tokei/releases/download/v{{ tokei_version }}/tokei-x86_64-unknown-linux-gnu.tar.gz"
    extract: true

  - name: xsv
    url: "https://github.com/BurntSushi/xsv/releases/download/{{ xsv_version }}/xsv-{{ xsv_version }}-x86_64-unknown-linux-musl.tar.gz"
    extract: true

  - name: yq
    url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64"
    bin_name: yq_linux_amd64

  - name: zoxide
    url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide-v{{ zoxide_version }}-x86_64-unknown-linux-musl.tar.gz"
    extract: true

  - name: viddy
    url: "https://github.com/sachaos/viddy/releases/download/v{{ viddy_version }}/viddy_{{ viddy_version }}_Linux_x86_64.tar.gz"
    extract: true
