---
- name: Install Goland
  kewlfft.aur.aur:
    name: goland
    use: aut
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install VSCode
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: aut
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
