---
- name: Install Pycharm
  become: true
  kewlfft.aur.aur:
    name: pycharm
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Intellij
  become: true
  kewlfft.aur.aur:
    name: intellij-idea-ultimate-edition
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Webstorm
  become: true
  kewlfft.aur.aur:
    name: webstorm
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Webstorm JRE
  become: true
  kewlfft.aur.aur:
    name: webstorm-jre
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Clion tasks
  ansible.builtin.include_tasks: clion.yml

- name: Install Goland
  become: true
  kewlfft.aur.aur:
    name: goland
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Goland JRE
  become: true
  kewlfft.aur.aur:
    name: goland-jre
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install VSCode
  become: true
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur


- name: Install development CLI tools
  become: true
  ansible.builtin.package:
    name:
      - golangci-lint
      - python-lsp-server
      - meld
      - kdiff3
    state: present
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install DevPod from AUR
  become: true
  kewlfft.aur.aur:
    name: devpod-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
