---
- name: Install Pycharm
  become: true
  kewlfft.aur.aur:
    name: pycharm-professional
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Intellij
  become: true
  kewlfft.aur.aur:
    name: intellij-idea-ultimate-edition
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Webstorm
  become: true
  kewlfft.aur.aur:
    name: webstorm
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Webstorm JRE
  become: true
  kewlfft.aur.aur:
    name: webstorm-jre
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Clion
  become: true
  kewlfft.aur.aur:
    name: clion
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Clion GDB
  become: true
  kewlfft.aur.aur:
    name: clion-gdb
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Clion LLDB
  become: true
  kewlfft.aur.aur:
    name: clion-lldb
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Goland
  become: true
  kewlfft.aur.aur:
    name: goland
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Goland JRE
  become: true
  kewlfft.aur.aur:
    name: goland-jre
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install VSCode
  become: true
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Windsurf
  become: true
  kewlfft.aur.aur:
    name: windsurf
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
