---
- name: Check if rustup is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.cargo/bin/rustup"
  register: rustup_installed
  vars:
    user_home: "{{ ansible_env.HOME }}"

- name: Download rustup installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: '0755'
  when: not rustup_installed.stat.exists

- name: Install Rust via rustup
  ansible.builtin.command:
    cmd: /tmp/rustup-init.sh -y --default-toolchain stable
  when: not rustup_installed.stat.exists
  changed_when: true

- name: Source cargo environment
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: 'source "$HOME/.cargo/env"'
    create: true
    mode: '0644'
  vars:
    user_home: "{{ ansible_env.HOME }}"

- name: Install cargo packages
  ansible.builtin.command:
    cmd: "{{ user_home }}/.cargo/bin/cargo install {{ item }}"
  loop: "{{ cargo_packages | default([]) }}"
  register: cargo_install
  changed_when: "'Installing' in cargo_install.stderr or 'Installed' in cargo_install.stdout"
  failed_when: cargo_install.rc != 0 and 'already installed' not in cargo_install.stderr
  vars:
    user_home: "{{ ansible_env.HOME }}"
