---
- name: Restart tlp
  become: true
  ansible.builtin.service:
    name: tlp.service
    state: restarted

- name: Restart power monitor
  become: true
  ansible.builtin.service:
    name: power_monitor.service
    state: restarted

- name: Restart charge control
  become: true
  ansible.builtin.service:
    name: charge_control.service
    state: restarted
