---
- name: Install Bash
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install Zsh
  package:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Install Starship
  package:
    name:
      - ttf-nerd-fonts-symbols-mono
      - starship
    state: present
  tags:
    - shell

- name: Install blesh
  kewlfft.aur.aur:
    name: blesh
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
