---
- name: Install Bash
  become: true
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install Zsh
  become: true
  package:
    name:
      - zsh
    state: present
  tags:
    - shell
