---
- name: Install Bash
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install Zsh
  package:
    name:
      - zsh
    state: present
  tags:
    - shell

- name: Install Zsh Completions
  package:
    name:
      - zsh-completions
    state: present
  tags:
    - shell
  when: ansible_os_family == "Archlinux"

- name: Install Starship
  package:
    name:
      - starship
    state: present
  tags:
    - shell
  when: ansible_os_family == "Archlinux"

- name: Install blesh
  kewlfft.aur.aur:
    name: blesh
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
