---
- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present
  become: true

- name: Include neovim tasks
  ansible.builtin.include_tasks: neovim.yml

- name: Include emacs tasks
  ansible.builtin.include_tasks: emacs.yml
