---
- name: Add Neovim stable PPA repository
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/stable
  when: ansible_distribution == 'Ubuntu'

- name: Install Neovim
  package:
    name: neovim
    state: present
  become: yes

- name: Clone NeoVim config
  git:
    clone: true
    repo: git@github.com:floatingman/nvim.git
    dest: "/home/{{ user }}/.config/nvim"
    accept_hostkey: yes
    update: yes
  become: yes
  become_user: "{{ user }}"
