---
- name: Install mpv
  package:
    name: mpv
    state: present
  become: true

- name: Push play script
  copy:
    src: play.sh
    dest: /usr/local/bin/play
    mode: 0755
  become: true

- name: Install Subliminal for sub download
  kewlfft.aur.aur:
    name: subliminal
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

# - name: Install ffsubsync for sub sync
#   kewlfft.aur.aur:
#     name: python-ffsubsync
#     use: auto
#     state: present
#   become_user: aur_builder
#   when: ansible_facts["os_family"] == "Archlinux"
#   tags:
#     - aur

# - name: Install alass for sub sync
#   kewlfft.aur.aur:
#     name: alass-git
#     use: auto
#     state: present
#   become_user: aur_builder
#   when: ansible_facts["os_family"] == "Archlinux"
#   tags:
#     - aur

- name: Install mpv sockets plugin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wis/mpvSockets/master/mpvSockets.lua
    dest: ~/.config/mpv/scripts/mpvSockets.lua
    mode: "755"
  become_user: "{{user.name}}"

- name: Install mpv-reload script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/4e6/mpv-reload/master/reload.lua
    dest: ~/.config/mpv/scripts/reload.lua
    mode: "755"
  become_user: "{{user.name}}"
