---
- name: Install mpv
  package:
    name: mpv
    state: present
  become: true

- name: Push play script
  copy:
    src: play.sh
    dest: /usr/local/bin/play
    mode: 0755
  become: true

- name: Install mpv sockets plugin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wis/mpvSockets/master/mpvSockets.lua
    dest: ~/.config/mpv/scripts/mpvSockets.lua
    mode: "755"
  become_user: "{{user.name}}"

- name: Install mpv-reload script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/4e6/mpv-reload/master/reload.lua
    dest: ~/.config/mpv/scripts/reload.lua
    mode: "755"
  become_user: "{{user.name}}"
