---
- name: Playbook
  hosts: localhost
  connection: local
  roles:
    - { role: ansible-role-basic, tags: ["basic"] }
    - { role: ansible-role-system, tags: ["system"] }
    - { role: ansible-role-shell, tags: ["shell"] }
    - { role: ansible-role-dotfiles, tags: ["dotfiles"] }
    - { role: ansible-role-packages, tags: ["packages"] }
    - { role: ansible-role-pip, tags: ["pip"] }
    - { role: ansible-role-asdf, tags: ["asdf"] }
    - { role: neovim, tags: ["neovim"] }
    - { role: ansible-role-binaries, tags: ["binaries"], when: ansible_os_family == "Debian" }
    - { role: avanov.pyenv, tags: ["python"] }
