---
- name: Playbook
  hosts: localhost
  connection: local
  roles:
    - role: ansible-role-basic
    - role: ansible-role-system
    - role: ansible-role-shell
    - role: ansible-role-dotfiles
    - role: ansible-role-packages
    - role: ansible-role-pip
    - role: ansible-role-binaries
