---
roles:
  - name: ansible-role-shell
    src: https://github.com/floatingman/ansible-role-shell.git
    scm: git
    version: master

  - name: ansible-role-binaries
    src: https://github.com/Allaman/ansible-role-binaries.git
    scm: git
    version: master

  - name: ansible-role-packages
    src: https://github.com/floatingman/ansible-role-packages.git
    scm: git
    version: master

  - name: ansible-role-pip
    src: https://github.com/Allaman/ansible-role-pip.git
    scm: git
    version: main

  - name: ansible-role-asdf
    src: https://github.com/floatingman/ansible-role-asdf.git
    scm: git
    version: master

  - name: avanov.pyenv
    src: https://github.com/avanov/ansible-galaxy-pyenv
    scm: git
    version: master

collections:
  - name: kewlfft.aur
