---
- name: Install Obsidian On Arch
  become: true
  package:
    name: obsidian
    state: present
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - notes

- name: Install Obsidian on Debian
  become: true
  flatpak:
    name: md.obsidian.Obsidian
    state: present
  when: ansible_facts["os_family"] != "Archlinux"
  tags:
    - notes
