---
- name: Install chezmoi on Arch
  become: true
  kewlfft.aur.aur:
    name: chezmoi
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install chezmoi on Ubuntu or Debian via Homebrew
  community.general.homebrew:
    name: chezmoi
    state: present
  when: ansible_facts["os_family"] == "Debian"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: Initialize user dotfiles with chezmoi
  become: true
  ansible.builtin.command: >
    chezmoi init
    --apply
    --source="{{ dotfiles_config.repo_url }}"
    --branch="{{ dotfiles_config.branch | default('main') }}"
  changed_when: true
  when: dotfiles_config is defined
  become_user: "{{ user.name }}"
  environment:
    HOME: "/home/{{ user.name }}"

- name: Create global gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "/home/{{ user.name }}/.gitconfig"
    force: true
    mode: '0644'
