---
- name: Set cron package and service name
  ansible.builtin.set_fact:
    cron_package: "{{ {'RedHat': 'cronie', 'Archlinux': 'cronie'} | combine({'Debian': 'cron'}) }}"
    cron_service: "{{ {'RedHat': 'cronie', 'Archlinux': 'cronie'} | combine({'Debian': 'cron'}) }}"

- name: Install cron
  become: true
  ansible.builtin.package:
    name: "{{ cron_package[ansible_facts['os_family']] }}"
    state: present

- name: Enable cron
  become: true
  ansible.builtin.service:
    name: "{{ cron_service[ansible_facts['os_family']] }}"
    enabled: true
    state: started
