---
- name: Install android-tools
  become: true
  package:
    name: android-tools
    state: present
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install android-tools
  become: true
  package:
    name: android-platform-tools-base
    state: present
  when: ansible_facts["os_family"] != "Archlinux"

- name: Install android-udev
  become: true
  package:
    name: android-udev
    state: present
  when: ansible_facts["os_family"] == "Archlinux"

- name: Add {{ user.name }} to adbusers group
  become: true
  user:
    name: "{{ user.name }}"
    groups: adbusers
    append: yes
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - user
