---
- name: Install autocutsel
  kewlfft.aur.aur:
    name: autocutsel
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - autocutsel
    - aur
