---
- name: Install gnupg
  package:
    name: gnupg
    state: present
  become: true

- name: Enable gpg-agent.socket
  ansible.builtin.systemd:
    name: gpg-agent.socket
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: gnupg.enable_agent == True

- name: Enable dirmngr.socket
  ansible.builtin.systemd:
    name: dirmngr.socket
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: gnupg.enable_agent == True

- name: Enable gpg-agent-ssh.socket
  ansible.builtin.systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: gnupg.enable_agent == True and gnupg.emulate_ssh == True
