---
- name: Install OpenSSH
  become: true
  package:
    name: openssh
    state: present
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install OpenSSH
  become: true
  package:
    name: ssh
    state: present
  when: ansible_facts["os_family"] != "Archlinux"

- name: Push OpenSSH daemon configuration file
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd

- name: Enable and start OpenSSH
  become: true
  service:
    name: sshd.service
    enabled: yes
    state: started
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True and ansible_facts["os_family"] == "Archlinux"

- name: Disable and stop OpenSSH
  become: true
  service:
    name: sshd.service
    enabled: no
    state: stopped
  when: ssh.enable_sshd is defined and ssh.enable_sshd == False

- name: Install sshfs
  become: true
  package:
    name: sshfs
    state: present

- name: Install autossh
  become: true
  package:
    name: autossh
    state: present

- name: Copy fuse configuration file
  become: true
  copy:
    src: fuse.conf
    dest: /etc/fuse.conf

- name: Install keychain
  become: true
  package:
    name: keychain
    state: present

- name: Install x11-ask-pass
  become: true
  package:
    name: x11-ssh-askpass
    state: present
  when: "display_manager is defined and ansible_facts['os_family'] == 'Archlinux'"

- name: Export SSH_ASKPASS environment variable
  become: true
  lineinfile:
    dest: /etc/profile
    state: present
    line: 'export SSH_ASKPASS="/usr/lib/ssh/x11-ssh-askpass"'
  when: "display_manager is defined"

- name: Make directory for user SSH key
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install user SSH key
  copy:
    src: "{{ ssh.user_key }}"
    dest: /home/{{ user.name }}/.ssh/id_rsa
    mode: 600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: ssh.user_key is defined

- name: Install Mosh
  become: true
  package:
    name: mosh
    state: present
