---
- name: Check if original hosts backup file exists
  stat:
    path: "{{ hosts_backup }}"
  register: stat_result

- name: Backup original hosts file
  become: true
  copy:
    src: "{{ hosts_path }}"
    dest: "{{ hosts_backup }}"
    force: yes
  when: not stat_result.stat.exists

- name: Restore original hosts file
  become: true
  copy:
    src: "{{ hosts_backup }}"
    dest: "{{ hosts_path }}"
  when: stat_result.stat.exists

- name: Delete backup of original hosts file
  become: true
  file:
    path: "{{ hosts_backup }}"
    state: absent
  when: stat_result.stat.exists

- name: Set hosts file
  become: true
  get_url:
    force: yes
    url: "{{ hosts_url }}"
    dest: "{{ hosts_path }}"
    group: root
    owner: root
