---
- name: Check if original hosts backup file exists
  ansible.builtin.stat:
    path: "{{ hosts_backup }}"
  register: stat_result

- name: Backup original hosts file
  become: true
  ansible.builtin.copy:
    src: "{{ hosts_path }}"
    dest: "{{ hosts_backup }}"
    force: true
  when: not stat_result.stat.exists

- name: Restore original hosts file
  become: true
  ansible.builtin.copy:
    src: "{{ hosts_backup }}"
    dest: "{{ hosts_path }}"
  when: stat_result.stat.exists

- name: Delete backup of original hosts file
  become: true
  ansible.builtin.file:
    path: "{{ hosts_backup }}"
    state: absent
  when: stat_result.stat.exists

- name: Set hosts file
  become: true
  ansible.builtin.get_url:
    force: true
    url: "{{ hosts_url }}"
    dest: "{{ hosts_path }}"
    group: root
    owner: root
