---
- name: Allow sudo without password
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ user.name }}	ALL=NOPASSWD: ALL"
    insertafter: '^%admin\tALL=\(ALL\) ALL'
    validate: "visudo -cf %s"
  when: sudo_without_password|default(false) == true

- name: Ensures /etc/keyd/ exists
  become: true
  file:
    path: /etc/keyd
    state: directory

- name: Install keyd-git
  kewlfft.aur.aur:
    name: keyd-git
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["distribution"] == "Archlinux"

- name: Remove old versions of keyd
  become: true
  ansible.builtin.file:
    path: "/home/{{ user.name }}/git/keyd"
    state: absent
  when: ansible_facts["distribution"] == "Debian"

- name: Clone keyd
  ansible.builtin.git:
    repo: https://github.com/rvaiya/keyd
    dest: "/home/{{ user.name }}/git/keyd"
  when: ansible_facts["distribution"] == "Debian"

- name: Make keyd from source
  ansible.builtin.command: make 
  args:
    chdir: "/home/{{ user.name }}/git/keyd"
  when: ansible_facts["distribution"] == "Debian"

- name: Install keyd from source
  ansible.builtin.command: sudo make install
  args:
    chdir: "/home/{{ user.name }}/git/keyd"
  when: ansible_facts["distribution"] == "Debian"

- name: Enable and start keyd service
  service:
    name: keyd
    state: started
    enabled: yes
  become: true

- name: Copy keyd config file
  become: true
  copy:
    src: "keyd_default.conf"
    dest: /etc/keyd/default.conf
    owner: root
    group: root
  notify:
    - reload systemd config

- name: Install hdparm
  become: true
  package:
    name: hdparm
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start weekly filesystem TRIM timer
  become: true
  service:
    name: fstrim.timer
    enabled: yes
  when: ansible_facts["distribution"] == "Archlinux"
