---
- name: Install hdparm
  become: true
  package:
    name: hdparm
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start weekly filesystem TRIM timer
  become: true
  ansible.builtin.service:
    name: fstrim.timer
    enabled: true
  when: ansible_facts["distribution"] == "Archlinux"
