---
- name: Allow sudo without password
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
    insertafter: '^%admin\tALL=\(ALL\) ALL'
    validate: "visudo -cf %s"
  when: sudo_without_password|default(false) == true

- name: Ensures /etc/keyd/ exists
  become: yes
  file:
    path: /etc/keyd
    state: directory
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install keyd-git
  kewlfft.aur.aur:
    name: keyd-git
    use: auto
    state: present
  become: yes
  become_user: "{{ ansible_user_id }}"
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start keyd service
  service:
    name: keyd
    state: started
    enabled: yes
  become: yes
  when: ansible_facts["distribution"] == "Archlinux"

- name: Copy keyd config file
  become: yes
  copy:
    src: "keyd_default.conf"
    dest: /etc/keyd/default.conf
    owner: root
    group: root
  notify:
    - reload systemd config
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install hdparm
  become: yes
  pacman:
    name: hdparm
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start weekly filesystem TRIM timer
  become: yes
  service:
    name: fstrim.timer
    enabled: yes
  when: ansible_facts["distribution"] == "Archlinux"
