---
- name: Install GOESImage
  become: true
  kewlfft.aur.aur:
    name: goesimage
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Push GOESImage service file
  ansible.builtin.template:
    src: goesimage.service.j2
    dest: /etc/systemd/user/goesimage.service
    mode: '0644'
  become: true
  notify:
    - reload systemd config

- name: Push GOESImage timer file
  ansible.builtin.template:
    src: goesimage.timer.j2
    dest: /etc/systemd/user/goesimage.timer
    mode: '0644'
  become: true
  notify:
    - reload systemd config
    - Restart GOESImage

- name: Enable and start goesimage.timer for user
  ansible.builtin.systemd:
    name: goesimage.timer
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: goesimage.run_on == "all"

- name: Disable goesimage.timer for user
  ansible.builtin.systemd:
    name: goesimage.timer
    enabled: false
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: goesimage.run_on != "all"

- name: Add goesimage.timer to nmtrust trusted unit list
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: present
    line: "goesimage.timer,user:{{ user.name }}"
  when: goesimage.run_on == "trusted"
  become: true

- name: Remove goesimage.timer from nmtrust trusted unit list
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: absent
    line: "goesimage.timer,user:{{ user.name }}"
  when: goesimage.run_on != "trusted"
  become: true
