---
- name: Install fw-ectool-git
  kewlfft.aur.aur:
    name: fw-ectool-git
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
    - framework

- name: Copy charge control service
  become: true
  copy:
    src: chargecontrol.service
    dest: /etc/systemd/system/
  notify:
    - reload systemd config
    - restart charge control
  tags:
    - framework

- name: Enable and start charge control service
  become: true
  service:
    name: chargecontrol.service
    enabled: yes
    state: started
  tags:
    - framework
