---
- name: Install TLP
  become: true
  package:
    name:
      - ethtool
      - tlp
      - tlp-rdw
    state: present
  tags:
    - tlp

- name: Push TLP battery threshold config
  become: true
  copy:
    src: tlp/20-battery.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Push TLP radio device config
  become: true
  copy:
    src: tlp/20-rdw.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Push TLP PCIe config
  become: true
  copy:
    src: tlp/20-pcie.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Mask systemd radio service
  become: true
  command: systemctl mask systemd-rfkill.service
  tags:
    - tlp

- name: Mask systemd radio socket
  become: true
  command: systemctl mask systemd-rfkill.socket
  tags:
    - tlp

- name: Enable TLP
  become: true
  service:
    name: tlp.service
    enabled: yes
  tags:
    - tlp
