---
- name: Install TuneD
  become: true
  package:
    name: tuned-ppd
    state: present
  tags:
    - tuned

- name: Enable and start TuneD
  become: true
  ansible.builtin.service:
    name: tuned.service
    enabled: true
    state: started
  tags:
    - tuned

- name: Install power monitor script
  become: true
  ansible.builtin.copy:
    src: power_monitor.sh
    dest: /usr/local/bin/
    mode: 0755
  notify:
    - restart power monitor
  tags:
    - tuned

- name: Copy power monitor service
  become: true
  ansible.builtin.copy:
    src: power_monitor.service
    dest: /etc/systemd/system/
  notify:
    - reload systemd config
    - restart power monitor
  tags:
    - tuned

- name: Enable and start power monitor service
  become: true
  ansible.builtin.service:
    name: power_monitor.service
    enabled: true
    state: started
  tags:
    - tuned
