---
- name: Install pass
  package:
    name: pass
    state: present
  become: true

- name: Install pass-otp
  package:
    name: pass-otp
    state: present
  become: true

- name: Install rofi-pass
  package:
    name: rofi-pass
    state: present
  become: true
  tags:
    - rofi

- name: Install pass-update
  become: true
  kewlfft.aur.aur:
    name: pass-update
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install pwgen-passphrase
  become: true
  kewlfft.aur.aur:
    name: pwgen-passphrase
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
