---
# - name: Download the i3wm signing key (tarball) from sur5r.net
#   ansible.builtin.get_url:
#     url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb
#     dest: /tmp/keyring.deb
#     checksum: sha256:2c2601e6053d5c68c2c60bcd088fa9797acec5f285151d46de9c830aaba6173c
#
# - name: Install sur5r's i3wm signing key
#   become: true
#   ansible.builtin.apt:
#     deb: /tmp/keyring.deb
#
# - name: Add sur5r's i3 repository into sources list
#   become: true
#   ansible.builtin.apt_repository:
#     repo: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
#     state: present
#     filename: sur5r-i3

- name: Install i3
  become: true
  ansible.builtin.apt:
    name: i3
    update_cache: yes
