---
- name: Install i3 for Arch
  include_tasks: i3-arch.yml
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install i3 for Debian
  include_tasks: i3-debian.yml
  when: ansible_facts["os_family"] == "Debian"

- name: Install i3
  become: true
  package:
    name:
      - i3-wm
      - i3blocks
      - i3status
    state: present

- name: Install py3status
  become: true
  package:
    name:
      - py3status
    state: present

- name: Verify that default applications file exists
  become: true
  copy:
    content: ""
    dest: /etc/xdg/mimeapps.list
    force: false

- name: Verify header in default applications file
  become: true
  lineinfile: dest=/etc/xdg/mimeapps.list
    state=present
    line='[Default Applications]'
    insertbefore=BOF

- name: Install dunst
  become: true
  package:
    name: dunst
    state: present

- name: Install dmenu
  become: true
  package:
    name: dmenu
    state: present

- name: Install autotiling
  kewlfft.aur.aur:
    name: autotiling
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- include_tasks: rofi.yml
