---
galaxy_info:
  author: Daniel Newman
  description: Install and manage Bibata cursor themes
  company:
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - cursor
    - theme
    - desktop
    - gui
    - bibata

dependencies: []
