---
- name: Reconfigure NVIDIA if needed
  when: "'nvidia' in _drivers_to_install"
  block:
    - name: Update NVIDIA initramfs
      ansible.builtin.command: mkinitcpio -P
      become: true
      changed_when: true

    - name: Restart display manager
      ansible.builtin.systemd:
        name: "{{ display_manager }}"
        state: restarted
      become: true
      when: display_manager is defined
