---
# tasks file for homebrew
- name: Check if Homebrew is already installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew_check

- name: Install Homebrew dependencies (Debian/Ubuntu)
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
    update_cache: yes
  become: true
  when:
    - ansible_os_family == "Debian"
    - not homebrew_check.stat.exists

- name: Install Homebrew dependencies (Arch)
  pacman:
    name:
      - base-devel
      - curl
      - file
      - git
    state: present
  become: true
  when:
    - ansible_os_family == "Archlinux"
    - not homebrew_check.stat.exists

- name: Download and install Homebrew
  shell: |
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  when: not homebrew_check.stat.exists

- name: Add Homebrew to PATH in shell profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      # Homebrew
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Homebrew"
    create: yes
  when: not homebrew_check.stat.exists

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: no
    path: /home/linuxbrew/.linuxbrew/bin
  when: homebrew_update | default(true) and homebrew_check.stat.exists

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    path: /home/linuxbrew/.linuxbrew/bin
  loop: "{{ homebrew_packages | default([]) }}"
  when: homebrew_packages is defined and homebrew_packages | length > 0
