---
- name: Install twitch streamlink
  kewlfft.aur.aur:
    name: streamlink-twitch-gui-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install chatty
  kewlfft.aur.aur:
    name: chatty
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
