---
- name: Install Thunar
  become: true
  package:
    name: thunar
    state: present

- name: Install Thunar plugins
  become: true
  package:
    name:
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
    state: present

- name: Install GVFS for filesharing functionality
  become: true
  package:
    name:
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
    state: present
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install GVFS for filesharing functionality
  become: true
  package:
    name:
      - gvfs
    state: present
  when: ansible_facts["os_family"] != "Archlinux"
