---
- name: Install Thunar
  package:
    name: thunar
    state: present
  become: true

- name: Install Thunar plugins
  package:
    name:
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
    state: present
  become: true

- name: Install GVFS for filesharing functionality
  package:
    name:
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
    state: present
  become: true
