---
- name: Install helm
  become: true
  community.general.pacman:
    name: helm
    state: present

- name: Install kubectl
  become: true
  community.general.pacman:
    name: kubectl
    state: present
