---
- name: Install helm
  become: true
  community.general.pacman:
    name: helm
    state: present

- name: Install kubectl
  become: true
  community.general.pacman:
    name: kubectl
    state: present

- name: Install kubecm
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: kubecm-git
    use: auto
    state: present
  tags:
    - aur
