---
- name: Install qutebrowser dependencies
  package:
    name:
      - python-adblock
      - pdfjs
    state: present
  tags:
    - qutebrowser

- name: Install Firefox
  package:
    name:
      - firefox
      - speech-dispatcher
    state: present
  tags:
    - firefox

- name: Install Google Chrome
  kewlfft.aur.aur:
    name: google-chrome
    use: auto
    state: present
  become: true
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Tor browser
  package:
    name: torbrowser-launcher
    state: present
  tags:
    - tor-browser

- name: Push rofi browser chooser
  ansible.builtin.template:
    src: browser.sh.j2
    dest: /usr/local/bin/browser
    mode: "0755"
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  ansible.builtin.file:
    path: /usr/local/share/applications
    state: directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  ansible.builtin.copy:
    src: browser.desktop
    dest: /usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Verify mimeapps.list exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/xdg/mimeapps.list
    force: false
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  ansible.builtin.lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^text/html=", line: "text/html=browser.desktop" }
    - { regexp: "^text/xml=", line: "text/xml=browser.desktop" }
    - { regexp: "^text/mml=", line: "text/mml=browser.desktop" }
    - {
        regexp: '^application/xhtml\+xml=',
        line: "application/xhtml+xml=browser.desktop",
      }
    - { regexp: "^application/xml=", line: "application/xml=browser.desktop" }
    - {
        regexp: "^x-scheme-handler/http=",
        line: "x-scheme-handler/http=browser.desktop",
      }
    - {
        regexp: "^x-scheme-handler/https=",
        line: "x-scheme-handler/https=browser.desktop",
      }
  tags:
    - rofi
    - chooser

- name: Configure surfraw browser
  ansible.builtin.lineinfile:
    dest: /etc/xdg/surfraw/conf
    regexp: "^def   SURFRAW_graphical_browser	"
    line: "def   SURFRAW_graphical_browser	/usr/local/bin/browser"
  tags:
    - surfraw
    - chooser

- name: Push surfraw-rofi script
  ansible.builtin.copy:
    src: surfraw-rofi
    dest: /usr/local/bin/surfraw-rofi
    mode: "0755"
  tags:
    - surfraw
    - rofi

- name: Install Microsoft Edge
  kewlfft.aur.aur:
    name: microsoft-edge-stable-bin
    use: auto
    state: present
  become: true
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
