---
- name: Install w3m
  package:
    name: w3m
    state: present
  become: true

- name: Install lynx
  package:
    name: lynx
    state: present
  become: true

- name: Install qutebrowser
  package:
    name:
      - qutebrowser
    state: present
  become: true
  tags:
    - qutebrowser

- name: Install surfraw
  package:
    name: surfraw
    state: present
  become: true
  tags:
    - surfraw

- name: Install browsers on Arch
  include_tasks: browsers-arch.yml
  when: ansible_facts["os_family"] == "Archlinux"

- name: Install browsers on Debian
  include_tasks: browsers-debian.yml
  when: ansible_facts["os_family"] != "Archlinux"
