---
# tasks file for ansible-role-binaries
- name: Ensure {{ temp_dir }} is present
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Ensure {{ local_bin_dir }} is present
  file:
    path: "{{ local_bin_dir }}"
    state: directory

- name: Downloading binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ temp_dir }}"
  register: download
  loop: "{{ binaries }}"

- name: Extracting packages
  unarchive:
    remote_src: true
    src: "{{ item.dest }}"
    dest: "{{ temp_dir }}"
    list_files: true
  loop: "{{ download.results }}"
  when:
    - item.item.extract is defined and item.item.extract == True

- name: Copy files to binary dir
  copy:
    remote_src: true
    src: "{{ (temp_dir, (item.item.bin_path | default('')), (item.item.bin_name | default(item.item.name)) ) | path_join}}"
    dest: "{{ (local_bin_dir,  item.item.name ) | path_join }}"
    mode: 0755
  loop: "{{ download.results }}"

- name: Creating file with test data
  copy:
    dest: "{{ temp_dir }}/binaries.txt"
    content: "{{ binaries }}"
  when: is_test is defined and is_test == True

- name: Ensure {{ tmp_dir }} is deleted
  file:
    path: "{{ temp_dir }}"
    state: absent
  when: is_test is not defined or is_test != True
