- name: Install Proton Bridge
  kewlfft.aur.aur:
    name:
      - protonmail-bridge-core
      - protonmail-bridge
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Proton VPN
  kewlfft.aur.aur:
    name: protonvpn
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Proton Pass
  kewlfft.aur.aur:
    name: proton-pass-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install Proton mail
  kewlfft.aur.aur:
    name: proton-mail-bin
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
