---
- name: Update APT package cache
  hosts: all
  become: true
  tags:
    - apt
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: update_apt_cache | bool
