---
- name: Check Linux requirements
  hosts: all
  tags:
    - always
    - linux
  tasks:
    - name: Check that we're running Linux
      assert:
        that:
          - ansible_system == 'Linux'
        msg: "This playbook only supports Linux systems"

    - name: Check that we're running supported Debian-based distribution
      assert:
        that:
          - ansible_distribution == 'Ubuntu'
            or ansible_distribution == 'Debian'
            or ansible_distribution == 'Pengwin'
        msg: "This playbook only supports Ubuntu, Debian and Pengwin distributions"

    - name: Check that 'user_home' is defined and not set to '/root'
      assert:
        that:
          - user_home is defined
          - user_home != '/root'

    - name: Check that 'user_name' is defined and not set to 'root'
      assert:
        that:
          - user_name is defined
          - user_name != 'root'
