---
- name: Install Synology Drive
  become: true
  kewlfft.aur.aur:
    name: synology-drive
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
