---
- name: Install alacritty
  package:
    name: alacritty
    state: present
  tags:
    - terminal

- name: Install kitty
  package:
    name: kitty
    state: present
  tags:
    - terminal

- name: Install Wezterm
  package:
    name: wezterm
    state: present
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - terminal

- name: Install Wezterm
  flatpak:
    name: org.wezfurlong.wezterm
    state: present
  when: ansible_facts["os_family"] != "Archlinux"
  tags:
    - terminal
