---
- name: Install alacritty
  become: true
  package:
    name: alacritty
    state: present
  tags:
    - terminal

- name: Install kitty
  become: true
  package:
    name: kitty
    state: present
  tags:
    - terminal

