---
- name: ensure fonts directory
  file:
    path: "/home/{{ user.name }}/.fonts"
    state: directory
  become: true
  become_user: "{{ user.name }}"

- name: Hack exists
  shell: "ls /home/{{ user.name }}/.fonts/Hack*Nerd*Font*"
  register: hack_exists
  ignore_errors: true
  become: true
  become_user: "{{ user.name }}"

- name: Download Hack
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz
    dest: "/home/{{ user.name }}/.fonts/"
    remote_src: yes
  become: true
  become_user: "{{ user.name }}"

- name: JetBrains exists
  shell: "ls /home/{{ user.name }}/.fonts/JetBrains*Nerd*Font*"
  register: jetbrains_exists
  ignore_errors: true
  become: true
  become_user: "{{ user.name }}"

- name: Download JetBrains Mono Nerd Font
  when: jetbrains_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
    dest: "/home/{{ user.name }}/.fonts/"
    remote_src: yes
  become: true
  become_user: "{{ user.name }}"
