---
- name: Install LightDM
  become: true
  ansible.builtin.package:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present

- name: Enable LightDM
  become: true
  ansible.builtin.service:
    name: lightdm.service
    enabled: true

- name: Create background dir
  become: true
  ansible.builtin.file:
    path: /usr/share/backgrounds
    state: directory
    mode: '0755'

- name: Push LightDM greeter background
  become: true
  ansible.builtin.copy:
    src: M31_Galex_960.jpg
    dest: /usr/share/backgrounds/M31_Galex_960.jpg
    mode: '0644'

- name: Specify LightDM greeter background
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: "^background="
    state: present
    line: "background=/usr/share/backgrounds/M31_Galex_960.jpg"

- name: Hide user images
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: "^hide-user-image="
    state: present
    line: "hide-user-image=true"

- name: Force LightDM greeter theme
  become: true
  ansible.builtin.lineinfile:
    dest: /usr/share/xgreeters/lightdm-gtk-greeter.desktop
    regexp: "^Exec="
    state: present
    line: "Exec=env GTK_THEME=Adwaita:dark lightdm-gtk-greeter"
