---
- name: Install Docker packages (Arch)
  become: true
  ansible.builtin.package:
    name:
      - runc
      - containerd
      - docker
      - docker-compose
      - docker-machine
    state: present
  when: ansible_facts['os_family'] == "Archlinux"
  tags:
    - docker

- name: Remove conflicting Docker CE packages (Debian)
  become: true
  ansible.builtin.package:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: absent
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - docker

- name: Install Docker packages (Debian)
  become: true
  ansible.builtin.package:
    update_cache: true
    name:
      - docker.io
      - docker-compose
    state: present
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - docker

- name: Enable Docker service
  become: true
  ansible.builtin.service:
    name: docker.service
    enabled: true

- name: Add user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
