---
- name: Install Docker
  become: true
  package:
    name:
      - runc
      - containerd
      - docker
      - docker-compose
      - docker-machine
    state: present
  tags:
    - docker

- name: Enable Docker service
  become: true
  ansible.builtin.service:
    name: docker.service
    enabled: true

- name: Add user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
