---
- name: install greenclip from AUR
  become: true
  kewlfft.aur.aur:
    name: rofi-greenclip
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: copy greenclip.service
  ansible.builtin.copy:
    src: greenclip.service
    dest: /etc/systemd/user/greenclip.service
  become: true

- name: Enable greenclip.service
  ansible.builtin.systemd:
    name: greenclip.service
    scope: user
    enabled: true
    state: started
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
