---
- name: Install sudo
  pacman:
    name: sudo
    state: present
  become: true
  tags:
    - sudo

- name: Add user to wheel group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: wheel
    append: true
  become: true
  tags:
    - sudo
    - user

- name: Copy sudo wheel group configuration
  ansible.builtin.template:
    src: sudo_wheel.j2
    dest: /etc/sudoers.d/01_wheel
    mode: 440
    validate: "visudo -cf %s"
  become: true
  tags:
    - sudo
