---
- name: Install alsa-utils
  ansible.builtin.package:
    name: alsa-utils
    state: present
  become: true

- name: Install Pipewire
  ansible.builtin.package:
    name:
      - pipewire
      - pipewire-pulse
      - pavucontrol
      - pavucontrol-qt
      - cava
      - wireplumber
      - playerctl
      - easyeffects
      - lsp-plugins-lv2
      - zam-plugins
      - calf
      - mda.lv2
    state: present
  become: true

- name: Install pasystray
  ansible.builtin.package:
    name: pasystray
    state: present
  become: true

- name: Install EasyEffects preset packs from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - easyeffects-bundy01-presets
      - easyeffects-digitalone1-presets-git
      - easyeffects-jtrv-presets-git
    use: auto
    state: present
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
