---
- name: Install xautolock
  package: 
    name: xautolock 
    state: present
  become: yes

- name: Install physlock
  package: 
    name: physlock
    state: present
  become: yes

- name: Install light for backlight management
  package:
    name: light
    state: present
  become: yes

- name: Push lock script
  copy: 
    src: lock.sh 
    dest: /usr/local/bin/lock 
    mode: 0755
  become: yes

- name: Push screen lock service file
  copy: 
    src: screenlock.service 
    dest: /etc/systemd/system/screenlock@.service
  become: yes
  notify:
    - reload systemd config

- name: Enable screen lock service
  service: 
    name: "screenlock@{{ user }}.service" 
    enabled: yes
  become: yes
