---
- name: Install xautolock
  package:
    name: xautolock
    state: present
  become: true

- name: Install xidlehook
  kewlfft.aur.aur:
    name: xidlehook
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install betterlockscreen
  kewlfft.aur.aur:
    name: betterlockscreen
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Push lock script
  copy:
    src: lock.sh
    dest: /usr/local/bin/lock
    mode: 0755
  become: true

- name: Push screen lock service file
  copy:
    src: screenlock.service
    dest: /etc/systemd/system/screenlock@.service
  become: true
  notify:
    - reload systemd config

- name: Enable screen lock service
  service:
    name: "screenlock@{{ user.name }}.service"
    enabled: yes
  become: true
