---
- name: Install xautolock
  package:
    name: xautolock
    state: present
  become: true

- name: Install xidlehook
  kewlfft.aur.aur:
    name: xidlehook
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Install betterlockscreen
  kewlfft.aur.aur:
    name: betterlockscreen
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur

- name: Push lock script
  ansible.builtin.copy:
    src: lock.sh
    dest: /usr/local/bin/lock
    mode: 'u=rwx,g=rx,o=rx'
  become: true

- name: Push screen lock service file
  ansible.builtin.copy:
    src: screenlock.service
    dest: /etc/systemd/system/screenlock@.service
    mode: 'u=rw,g=r,o=r'
  become: true
  notify:
    - reload systemd config

- name: Enable screen lock service
  ansible.builtin.service:
    name: "screenlock@{{ user.name }}.service"
    enabled: true
  become: true
  when: desktop_environment == 'i3'

- name: Disable screen lock service for non-i3
  ansible.builtin.service:
    name: "screenlock@{{ user.name }}.service"
    enabled: false
    state: stopped
  become: true
  when: desktop_environment != 'i3'
