---
- name: Install Syncthing
  become: true
  ansible.builtin.package:
    name: syncthing
    state: present

- name: Install Syncthingtray
  become: true
  community.general.pacman:
    name: syncthingtray
    state: present
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
