---
- name: Install Syncthing
  become: true
  package:
    name: syncthing
    state: present

- name: Install Syncthingtray
  become: true
  kewlfft.aur.aur:
    name: syncthingtray
    use: auto
    state: present
  become_user: aur_builder
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - aur
