---
- name: Install brightnessctl
  package:
    name: brightnessctl
    state: present

- name: Install illuminanced
  package:
    name: illuminanced
  when: illuminanced is defined

- name: Set max backlight file
  ansible.builtin.lineinfile:
    dest: /etc/illuminanced.toml
    regexp: ^max_backlight_file
    state: present
    line: 'max_backlight_file = "{{ illuminanced.max_backlight_file }}"'
  when: illuminanced.max_backlight_file is defined
  notify:
    - restart illuminanced

- name: Set backlight file
  ansible.builtin.lineinfile:
    dest: /etc/illuminanced.toml
    regexp: ^backlight_file
    state: present
    line: 'backlight_file = "{{ illuminanced.backlight_file }}"'
  when: illuminanced.backlight_file is defined
  notify:
    - restart illuminanced

- name: Set illuminance file
  ansible.builtin.lineinfile:
    dest: /etc/illuminanced.toml
    regexp: ^illuminance_file
    state: present
    line: 'illuminance_file = "{{ illuminanced.illuminance_file }}"'
  when: illuminanced.illuminance_file is defined
  notify:
    - restart illuminanced

- name: Set min backlight value
  ansible.builtin.lineinfile:
    dest: /etc/illuminanced.toml
    regexp: ^min_backlight
    state: present
    line: "min_backlight = {{ illuminanced.min_backlight }}"
  when: illuminanced.min_backlight is defined
  notify:
    - restart illuminanced

- name: Enable and start illuminanced
  ansible.builtin.service:
    name: illuminanced.service
    enabled: true
    state: started
  when: illuminanced is defined

- name: Install ddcutil
  package:
    name: ddcutil
    state: present

- name: Install geoclue
  package:
    name: geoclue
    state: present
